const DummyData = [
  {
    id: 1,
    orderType: "HORIZONTAL_VIDEO",
    footageUpload: "https://example.com/footage1",
    createdAt: "2024-07-13T00:00:00Z",
    updatedAt: "2024-07-13T00:00:00Z",
    rawVideoFootage: {
      id: 1,
      footageLength: 120,
      footageSize: 500,
      formDataId: 1,
    },
    orderLogistics: {
      id: 1,
      title: "Project 1",
      category: "Category A",
      description: "Description 1",
      date: "2024-07-13T00:00:00Z",
      finalLength: 120,
      formDataId: 1,
    },
    styleDetails: {
      id: 1,
      pacing: "Fast",
      tone: "Exciting",
      formDataId: 1,
    },
    orderDetails: {
      id: 1,
      editInstructions: "Quick cuts and high energy",
      exampleVideo: "https://example.com/example1",
      scriptLink: "https://example.com/script1",
      formDataId: 1,
    },
    addOns: ["THUMBNAIL", "FULL_VIDEO_CAPTION"],
  },
  {
    id: 2,
    orderType: "VERTICAL_VIDEO",
    footageUpload: "https://example.com/footage2",
    createdAt: "2024-07-13T00:00:00Z",
    updatedAt: "2024-07-13T00:00:00Z",
    rawVideoFootage: {
      id: 2,
      footageLength: 90,
      footageSize: 300,
      formDataId: 2,
    },
    orderLogistics: {
      id: 2,
      title: "Project 2",
      category: "Category B",
      description: "Description 2",
      date: "2024-07-14T00:00:00Z",
      finalLength: 90,
      formDataId: 2,
    },
    styleDetails: {
      id: 2,
      pacing: "Moderate",
      tone: "Informative",
      formDataId: 2,
    },
    orderDetails: {
      id: 2,
      editInstructions: "Include interview clips",
      exampleVideo: "https://example.com/example2",
      scriptLink: "https://example.com/script2",
      formDataId: 2,
    },
    addOns: ["VERTICAL_REFORMAT", "PROJECT_FILE"],
  },
  {
    id: 3,
    orderType: "CHANNEL_ASSETS",
    footageUpload: "https://example.com/footage3",
    createdAt: "2024-07-13T00:00:00Z",
    updatedAt: "2024-07-13T00:00:00Z",
    rawVideoFootage: {
      id: 3,
      footageLength: 60,
      footageSize: 150,
      formDataId: 3,
    },
    orderLogistics: {
      id: 3,
      title: "Project 3",
      category: "Category C",
      description: "Description 3",
      date: "2024-07-15T00:00:00Z",
      finalLength: 60,
      formDataId: 3,
    },
    styleDetails: {
      id: 3,
      pacing: "Slow",
      tone: "Relaxed",
      formDataId: 3,
    },
    orderDetails: {
      id: 3,
      editInstructions: "Focus on branding elements",
      exampleVideo: "https://example.com/example3",
      scriptLink: "https://example.com/script3",
      formDataId: 3,
    },
    addOns: ["SQUARE_REFORMAT", "THUMBNAIL"],
  },
  {
    id: 4,
    orderType: "THUMBNAIL",
    footageUpload: "https://example.com/footage4",
    createdAt: "2024-07-13T00:00:00Z",
    updatedAt: "2024-07-13T00:00:00Z",
    rawVideoFootage: {
      id: 4,
      footageLength: 45,
      footageSize: 100,
      formDataId: 4,
    },
    orderLogistics: {
      id: 4,
      title: "Project 4",
      category: "Category D",
      description: "Description 4",
      date: "2024-07-16T00:00:00Z",
      finalLength: 45,
      formDataId: 4,
    },
    styleDetails: {
      id: 4,
      pacing: "Moderate",
      tone: "Engaging",
      formDataId: 4,
    },
    orderDetails: {
      id: 4,
      editInstructions: "Highlight key points",
      exampleVideo: "https://example.com/example4",
      scriptLink: "https://example.com/script4",
      formDataId: 4,
    },
    addOns: ["HORIZONTAL_REFORMAT", "FULL_VIDEO_CAPTION"],
  },
  {
    id: 5,
    orderType: "HORIZONTAL_VIDEO",
    footageUpload: "https://example.com/footage5",
    createdAt: "2024-07-13T00:00:00Z",
    updatedAt: "2024-07-13T00:00:00Z",
    rawVideoFootage: {
      id: 5,
      footageLength: 180,
      footageSize: 700,
      formDataId: 5,
    },
    orderLogistics: {
      id: 5,
      title: "Project 5",
      category: "Category E",
      description: "Description 5",
      date: "2024-07-17T00:00:00Z",
      finalLength: 180,
      formDataId: 5,
    },
    styleDetails: {
      id: 5,
      pacing: "Fast",
      tone: "Energetic",
      formDataId: 5,
    },
    orderDetails: {
      id: 5,
      editInstructions: "Include action shots",
      exampleVideo: "https://example.com/example5",
      scriptLink: "https://example.com/script5",
      formDataId: 5,
    },
    addOns: ["THUMBNAIL", "PROJECT_FILE"],
  },
];
