import React from "react";
export const users = [
  {
    key: "1",
    order: "Tony Reichert",
    status: "Active",
    editorartist: "CEO",
    nextdraftin: "17days",
  },
  {
    key: "2",
    order: "Zoey Lang",
    status: "Paused",
    editorartist: "Technical Lead",
    nextdraftin: "72days",
  },
  {
    key: "3",
    order: "Jane Fisher",
    status: "Active",
    editorartist: "Senior Developer",
    nextdraftin: "5days",  
},
  {
    key: "4",
    order: "William Howard",
    status: "Vacation",
    editorartist: "Community Manager",
    nextdraftin: "3days",
  },
  {
    key: "5",
    order: "Emily Collins",
    status: "Active",
    editorartist: "Marketing Manager",
    nextdraftin: "2days",
  },
  {
    key: "6",
    order: "Brian Kim",
    status: "Active",
    editorartist: "Product Manager",
    nextdraftin: "12days",
  },
  {
    key: "7",
    order: "Laura Thompson",
    status: "Active",
    editorartist: "UX Designer",
    nextdraftin: "31days",
  },
  {
    key: "8",
    order: "Michael Stevens",
    status: "Paused",
    editorartist: "Data Analyst",
    nextdraftin: "2days",
  },
  {
    key: "9",
    order: "Sophia Nguyen",
    status: "Active",
    editorartist: "Quality Assurance",
    nextdraftin: "1days",
  },
  {
    key: "10",
    order: "James Wilson",
    status: "Vacation",
    editorartist: "Front-end Developer",
    nextdraftin: "5days",
  },
  {
    key: "11",
    order: "Ava Johnson",
    status: "Active",
    editorartist: "Back-end Developer",
    nextdraftin: "62days",
  },
  {
    key: "12",
    order: "Isabella Smith",
    status: "Active",
    editorartist: "Graphic Designer",
    nextdraftin: "22days",
  },
  {
    key: "13",
    order: "Oliver Brown",
    status: "Paused",
    editorartist: "Content Writer",
    nextdraftin: "2days",
  },
  {
    key: "14",
    order: "Lucas Jones",
    status: "Active",
    editorartist: "Project Manager",
    nextdraftin: "10days",
  },
];
